# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-mkdocs-5rc0-testing',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/nbdev-mkdocs-5rc0-testing',
                'lib_path': 'nbdev_mkdocs_5rc0_testing'},
  'syms': { 'nbdev_mkdocs_5rc0_testing.core': { 'nbdev_mkdocs_5rc0_testing.core.foo': ( 'core.html#foo',
                                                                                        'nbdev_mkdocs_5rc0_testing/core.py')}}}
